### ISSUE TITLE
Site won't load!

### ISSUE THREAD

**Issue by Audie36** [Audie36/snipcart-koajs#9]
When I try to deploy the application with `npm run dev`, I get the following:

```
> snipcart-koajs@2.0.0 dev /home/amoradi/snipcart-koajs
> nodemon index.js

[nodemon] 2.0.15
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node index.js`
/home/amoradi/snipcart-koajs/index.js:41
const Router = require('koa-router')
      ^

SyntaxError: Identifier 'Router' has already been declared
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by Audie36** [comment]
Fixed.  Web page is now visible
